### ISSUE TITLE
Support coursewise on/off

### ISSUE THREAD

**Issue by lucaboesch** [sharpchi/moodle-filter_syntaxhighlighter#3]
Hi and thanks for your great plugin!

In Moodle there is the possibility to mark a plugin as "Off, but available".
It then can be switched on on a course basis.
![filter_syntaxhighlighter_coursewise](https://user-images.githubusercontent.com/377279/44899668-a7b50b80-ad02-11e8-8deb-d7e991e01409.png)
Lecturers who then want this filter can switch it on in their course whereas throughout the whole Moodle instance it is generally switched of.
It seems to me that filter_syntaxhighlighter does not respect this setting. As soon as the filter is not set to "Disabeled", the syntax highlighting works everywhere, no matter if set to "On" or to "Off, but available".
Please enquire this bug.

Many thanks again for your contribution.

Best,
Luca

**Comment by sharpchi** [comment]
Hi Luca,
thanks for the feedback. The issue isn't exactly to do with the filter, rather than the CSS picking up you using `<pre><code></code></pre>` tags.
If the text you insert has those tags, the style sheets will still activate - remember all styles are loaded in the head. If you just use `<pre>` then the styles won't kick in.

Also, the filter really only does a filter on ``` backtick notation and replaces them with `<pre><code>` tags. If you have the filter off and are using the backticks then the code isn't styled.
